
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Mar 25 2025 18:55:26 IST (Mar 25 2025 13:25:26 UTC)

// Verification Directory fv/adder 

module adder(clk, a, b, sum, cout);
  input clk;
  input [7:0] a, b;
  output [7:0] sum;
  output cout;
  wire clk;
  wire [7:0] a, b;
  wire [7:0] sum;
  wire cout;
  wire [7:0] t1;
  wire [7:0] t2;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  DFFHQX1 \sum_reg[7] (.CK (clk), .D (n_15), .Q (sum[7]));
  DFFHQX1 cout_reg(.CK (clk), .D (n_14), .Q (cout));
  ADDFX1 g739__2398(.A (t1[7]), .B (t2[7]), .CI (n_12), .CO (n_14), .S
       (n_15));
  DFFHQX1 \sum_reg[6] (.CK (clk), .D (n_13), .Q (sum[6]));
  ADDFX1 g741__5107(.A (t1[6]), .B (t2[6]), .CI (n_10), .CO (n_12), .S
       (n_13));
  DFFHQX1 \sum_reg[5] (.CK (clk), .D (n_11), .Q (sum[5]));
  ADDFX1 g743__6260(.A (t1[5]), .B (t2[5]), .CI (n_8), .CO (n_10), .S
       (n_11));
  DFFHQX1 \sum_reg[4] (.CK (clk), .D (n_9), .Q (sum[4]));
  ADDFX1 g745__4319(.A (t1[4]), .B (t2[4]), .CI (n_6), .CO (n_8), .S
       (n_9));
  DFFHQX1 \sum_reg[3] (.CK (clk), .D (n_7), .Q (sum[3]));
  ADDFX1 g747__8428(.A (t1[3]), .B (t2[3]), .CI (n_4), .CO (n_6), .S
       (n_7));
  DFFHQX1 \sum_reg[2] (.CK (clk), .D (n_5), .Q (sum[2]));
  ADDFX1 g749__5526(.A (t1[2]), .B (t2[2]), .CI (n_2), .CO (n_4), .S
       (n_5));
  DFFHQX1 \sum_reg[1] (.CK (clk), .D (n_3), .Q (sum[1]));
  ADDFX1 g751__6783(.A (t1[1]), .B (t2[1]), .CI (n_0), .CO (n_2), .S
       (n_3));
  DFFQXL \sum_reg[0] (.CK (clk), .D (n_1), .Q (sum[0]));
  AOI2BB1XL g753__3680(.A0N (t2[0]), .A1N (t1[0]), .B0 (n_0), .Y (n_1));
  AND2XL g754__1617(.A (t2[0]), .B (t1[0]), .Y (n_0));
  DFFHQX1 \t1_reg[7] (.CK (clk), .D (a[7]), .Q (t1[7]));
  DFFHQX1 \t2_reg[1] (.CK (clk), .D (b[1]), .Q (t2[1]));
  DFFHQX1 \t2_reg[7] (.CK (clk), .D (b[7]), .Q (t2[7]));
  DFFHQX1 \t1_reg[5] (.CK (clk), .D (a[5]), .Q (t1[5]));
  DFFHQX1 \t1_reg[6] (.CK (clk), .D (a[6]), .Q (t1[6]));
  DFFHQX1 \t2_reg[3] (.CK (clk), .D (b[3]), .Q (t2[3]));
  DFFQXL \t1_reg[0] (.CK (clk), .D (a[0]), .Q (t1[0]));
  DFFQXL \t2_reg[0] (.CK (clk), .D (b[0]), .Q (t2[0]));
  DFFHQX1 \t1_reg[1] (.CK (clk), .D (a[1]), .Q (t1[1]));
  DFFHQX1 \t2_reg[6] (.CK (clk), .D (b[6]), .Q (t2[6]));
  DFFHQX1 \t1_reg[4] (.CK (clk), .D (a[4]), .Q (t1[4]));
  DFFHQX1 \t2_reg[4] (.CK (clk), .D (b[4]), .Q (t2[4]));
  DFFHQX1 \t1_reg[2] (.CK (clk), .D (a[2]), .Q (t1[2]));
  DFFHQX1 \t2_reg[5] (.CK (clk), .D (b[5]), .Q (t2[5]));
  DFFHQX1 \t1_reg[3] (.CK (clk), .D (a[3]), .Q (t1[3]));
  DFFHQX1 \t2_reg[2] (.CK (clk), .D (b[2]), .Q (t2[2]));
endmodule

