###############################################################
#  Generated by:      Cadence Innovus 23.13-s082_1
#  OS:                Linux x86_64(Host ID cadencea16)
#  Generated on:      Wed Mar 26 09:56:50 2025
#  Design:            adder
#  Command:           saveDesign adder_postroute
###############################################################
current_design adder
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clk}]  -name clk -period 10.000000 -waveform {0.000000 5.000000}
set_clock_transition  -rise -min 0.1 [get_clocks {clk}]
set_clock_transition  -rise -max 0.1 [get_clocks {clk}]
set_clock_transition  -fall -min 0.1 [get_clocks {clk}]
set_clock_transition  -fall -max 0.1 [get_clocks {clk}]
set_propagated_clock  [get_ports {clk}]
#END OF CLOCK SECTION#
set_wire_load_mode enclosed
set_clock_uncertainty  0.01 [get_ports {clk}]
