#==============================================================================
# Hierarchical dofile generated by Conformal LEC
# Version: 21.10-s300 (22-Aug-2021) (64 bit executable)
#------------------------------------------------------------------------------
# For additional reporting on 'not written' modules, see the 'VERBOSE REPORTING'
# section at the end of the hierarchical dofile
#------------------------------------------------------------------------------
# The command 'set module property' sets the instance context for the current
# root module. It is intended only for hierarchical comparison, and should
# not be modified by the user.
#------------------------------------------------------------------------------
# TERMS AND NOTATIONS USED
#------------------------------------------------------------------------------
# Module Instantiation Ratio: Average number of instantiations per matching module
# Wrapper size: #Logic gates enclosing the module's instance, and bounded by key-points
# Periphery size: #Logic gates in the fanin and fanout cone of instance's input and output boundary, and bounded by key-points
# 0: Indicates pin is constant zero
# 1: Indicates pin is constant one
# X: Indicates pin is full DC
# U: Indicates pin is unreachable
# Z: Indicates pin is floating
# KP<--: Indicates pin's fanin is directly connected to key-point (ignores buffers/inverters)
# -->KP: Indicates pin's fanout is directly connected to key-point (ignores buffers/inverters)
# REP: Indicates pin is representative pin
# EQ_REP: <polarity> rep_pinname>: Indicates pin is a member EQ pin with
# 'rep_pinname' specifying the representative, and 'polarity' specifying
# if it is positive or negative equivalent
# = : Indicates that the pins on LHS and RHS are mapped
# + : Indicates positive polarity for pin mapping
# - : Indicates negative polarity for pin mapping
# ? : Indicates unknown polarity for pin mapping
# G: Indicates that the pin belongs to Golden
# R: Indicates that the pin belongs to Revised
# IN: Indicates that the pin is an Input pin
# OUT: Indicates that the pin is an Output pin
# IO: Indicates that the pin is an Inout pin. Polarity of Inout pin is
#     always '?' because of name-only mapping
#==============================================================================

set_system_mode setup
vpxmode
delete set_seq_merge
set_seq_merge /K1_reg[2]  /K2_reg[3] -Golden
set_seq_merge /K1_reg[3]  /K2_reg[4] -Golden
set_seq_merge /K1_reg[4]  /K2_reg[5] -Golden
set_seq_merge /K1_reg[5]  /K2_reg[6] -Golden
set_seq_merge /K1_reg[7]  /K2_reg[8] -Golden
set_seq_merge /K1_reg[8]  /K2_reg[9] -Golden
set_seq_merge /K1_reg[9]  /K2_reg[10] -Golden
set_seq_merge /K1_reg[10]  /K2_reg[11] -Golden
set_seq_merge /K1_reg[11]  /K2_reg[12] -Golden
set_seq_merge /K1_reg[12]  /K2_reg[13] -Golden
set_seq_merge /K1_reg[13]  /K2_reg[14] -Golden
set_seq_merge /K1_reg[14]  /K2_reg[15] -Golden
set_seq_merge /K1_reg[15]  /K2_reg[16] -Golden
set_seq_merge /K1_reg[16]  /K2_reg[17] -Golden
set_seq_merge /K1_reg[17]  /K2_reg[18] -Golden
set_seq_merge /K1_reg[18]  /K2_reg[19] -Golden
set_seq_merge /K1_reg[19]  /K2_reg[20] -Golden
set_seq_merge /K1_reg[20]  /K2_reg[21] -Golden
set_seq_merge /K1_reg[21]  /K2_reg[22] -Golden
set_seq_merge /K1_reg[22]  /K2_reg[23] -Golden
set_seq_merge /K1_reg[23]  /K2_reg[24] -Golden
set_seq_merge /K1_reg[24]  /K2_reg[25] -Golden
set_seq_merge /K1_reg[25]  /K2_reg[26] -Golden
set_seq_merge /K1_reg[26]  /K2_reg[27] -Golden
set_seq_merge /K1_reg[27]  /K2_reg[28] -Golden
set_seq_merge /K1_reg[28]  /K2_reg[29] -Golden
set_seq_merge /K1_reg[29]  /K2_reg[30] -Golden
set_seq_merge /K1_reg[30]  /K2_reg[31] -Golden
set_seq_merge /K1_reg[31]  /K2_reg[32] -Golden
set_seq_merge /K1_reg[32]  /K2_reg[33] -Golden
set_seq_merge /K1_reg[33]  /K2_reg[34] -Golden
set_seq_merge /K1_reg[34]  /K2_reg[35] -Golden
set_seq_merge /K1_reg[35]  /K2_reg[36] -Golden
set_seq_merge /K1_reg[36]  /K2_reg[37] -Golden
set_seq_merge /K1_reg[37]  /K2_reg[38] -Golden
set_seq_merge /K1_reg[38]  /K2_reg[39] -Golden
set_seq_merge /K1_reg[39]  /K2_reg[40] -Golden
set_seq_merge /K1_reg[40]  /K2_reg[41] -Golden
set_seq_merge /K1_reg[41]  /K2_reg[42] -Golden
set_seq_merge /K1_reg[42]  /K2_reg[43] -Golden
set_seq_merge /K1_reg[43]  /K2_reg[44] -Golden
set_seq_merge /K1_reg[44]  /K2_reg[45] -Golden
set_seq_merge /K1_reg[45]  /K2_reg[46] -Golden
set_seq_merge /K1_reg[46]  /K2_reg[47] -Golden
set_seq_merge /K1_reg[47]  /K2_reg[48] -Golden
set_seq_merge /K1_reg[48]  /K2_reg[49] -Golden
set_seq_merge /K1_reg[49]  /K2_reg[50] -Golden
set_seq_merge /K1_reg[50]  /K2_reg[51] -Golden
set_seq_merge /K1_reg[51]  /K2_reg[52] -Golden
set_seq_merge /K1_reg[52]  /K2_reg[53] -Golden
set_seq_merge /K1_reg[53]  /K2_reg[54] -Golden
set_seq_merge /K1_reg[54]  /K2_reg[55] -Golden
set_seq_merge /K1_reg[55]  /K2_reg[56] -Golden
set_seq_merge /K1_reg[56]  /K2_reg[57] -Golden
set_seq_merge /K1_reg[57]  /K2_reg[58] -Golden
set_seq_merge /K1_reg[58]  /K2_reg[59] -Golden
set_seq_merge /K1_reg[59]  /K2_reg[60] -Golden
set_seq_merge /K1_reg[60]  /K2_reg[61] -Golden
set_seq_merge /K1_reg[61]  /K2_reg[62] -Golden
set_seq_merge /K1_reg[62]  /K2_reg[63] -Golden
set_seq_merge /K1_reg[63]  /K2_reg[64] -Golden
set_seq_merge /K1_reg[64]  /K2_reg[65] -Golden
set_seq_merge /K1_reg[65]  /K2_reg[66] -Golden
set_seq_merge /K1_reg[66]  /K2_reg[67] -Golden
set_seq_merge /K1_reg[67]  /K2_reg[68] -Golden
set_seq_merge /K1_reg[68]  /K2_reg[69] -Golden
set_seq_merge /K1_reg[69]  /K2_reg[70] -Golden
set_seq_merge /K1_reg[70]  /K2_reg[71] -Golden
set_seq_merge /K1_reg[71]  /K2_reg[72] -Golden
set_seq_merge /K1_reg[72]  /K2_reg[73] -Golden
set_seq_merge /K1_reg[73]  /K2_reg[74] -Golden
set_seq_merge /K1_reg[74]  /K2_reg[75] -Golden
set_seq_merge /K1_reg[75]  /K2_reg[76] -Golden
set_seq_merge /K1_reg[76]  /K2_reg[77] -Golden
set_seq_merge /K1_reg[77]  /K2_reg[78] -Golden
set_seq_merge /K1_reg[78]  /K2_reg[79] -Golden
set_seq_merge /K1_reg[79]  /K2_reg[80] -Golden
set_seq_merge /K1_reg[80]  /K2_reg[81] -Golden
set_seq_merge /K1_reg[81]  /K2_reg[82] -Golden
set_seq_merge /K1_reg[82]  /K2_reg[83] -Golden
set_seq_merge /K1_reg[83]  /K2_reg[84] -Golden
set_seq_merge /K1_reg[84]  /K2_reg[85] -Golden
set_seq_merge /K1_reg[85]  /K2_reg[86] -Golden
set_seq_merge /K1_reg[86]  /K2_reg[87] -Golden
set_seq_merge /K1_reg[87]  /K2_reg[88] -Golden
set_seq_merge /K1_reg[88]  /K2_reg[89] -Golden
set_seq_merge /K1_reg[89]  /K2_reg[90] -Golden
set_seq_merge /K1_reg[90]  /K2_reg[91] -Golden
set_seq_merge /K1_reg[91]  /K2_reg[92] -Golden
set_seq_merge /K1_reg[92]  /K2_reg[93] -Golden
set_seq_merge /K1_reg[93]  /K2_reg[94] -Golden
set_seq_merge /K1_reg[94]  /K2_reg[95] -Golden
set_seq_merge /K1_reg[95]  /K2_reg[96] -Golden
set_seq_merge /K1_reg[96]  /K2_reg[97] -Golden
set_seq_merge /K1_reg[97]  /K2_reg[98] -Golden
set_seq_merge /K1_reg[98]  /K2_reg[99] -Golden
set_seq_merge /K1_reg[99]  /K2_reg[100] -Golden
set_seq_merge /K1_reg[100]  /K2_reg[101] -Golden
set_seq_merge /K1_reg[101]  /K2_reg[102] -Golden
set_seq_merge /K1_reg[102]  /K2_reg[103] -Golden
set_seq_merge /K1_reg[103]  /K2_reg[104] -Golden
set_seq_merge /K1_reg[104]  /K2_reg[105] -Golden
set_seq_merge /K1_reg[105]  /K2_reg[106] -Golden
set_seq_merge /K1_reg[106]  /K2_reg[107] -Golden
set_seq_merge /K1_reg[107]  /K2_reg[108] -Golden
set_seq_merge /K1_reg[108]  /K2_reg[109] -Golden
set_seq_merge /K1_reg[109]  /K2_reg[110] -Golden
set_seq_merge /K1_reg[110]  /K2_reg[111] -Golden
set_seq_merge /K1_reg[111]  /K2_reg[112] -Golden
set_seq_merge /K1_reg[112]  /K2_reg[113] -Golden
set_seq_merge /K1_reg[113]  /K2_reg[114] -Golden
set_seq_merge /K1_reg[114]  /K2_reg[115] -Golden
set_seq_merge /K1_reg[115]  /K2_reg[116] -Golden
set_seq_merge /K1_reg[116]  /K2_reg[117] -Golden
set_seq_merge /K1_reg[117]  /K2_reg[118] -Golden
set_seq_merge /K1_reg[118]  /K2_reg[119] -Golden
set_seq_merge /K1_reg[119]  /K2_reg[120] -Golden
set_seq_merge /K1_reg[120]  /K2_reg[121] -Golden
set_seq_merge /K1_reg[121]  /K2_reg[122] -Golden
set_seq_merge /K1_reg[122]  /K2_reg[123] -Golden
set_seq_merge /K1_reg[123]  /K2_reg[124] -Golden
set_seq_merge /K1_reg[124]  /K2_reg[125] -Golden
set_seq_merge /K1_reg[125]  /K2_reg[126] -Golden
set_seq_merge /K1_reg[126]  /K2_reg[127] -Golden
set_seq_merge /K1_reg[127]  /K2_reg[0] -Golden
set_seq_merge /inst1_key_reg[23]  /inst1_key_reg[38] -Golden
set_seq_merge /inst1_key_reg[55]  /inst1_key_reg[70] -Golden
set_seq_merge /inst1_key_reg[106]  /inst1_key_reg[121] -Golden
set_seq_merge /inst1_key_reg[87]  /inst1_key_reg[102] -Golden
tclmode
# Comparing
#-------------------------------------------------------------------------------
# MODULE sbox (G) INSTANCE /inst1/s/sub_Bytes[0].s (G)
# MODULE sbox (R) INSTANCE /inst1_s_sub_Bytes[0].s (R)
# Wrapper size: (G) = 8  (R) = 16
# Periphery size: (G) = 2647  (R) = 1228
# Pins directly connected to key-points/constants: (G) = 50.00%  (R) = 50.00%
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) a[7]  (KP<--)(REP)  =   (R) a[7]  (KP<--)(REP) (by sim and name)
# IN (G) a[6]  (KP<--)(REP)  =   (R) a[6]  (KP<--)(REP) (by sim and name)
# IN (G) a[5]  (KP<--)(REP)  =   (R) a[5]  (KP<--)(REP) (by sim and name)
# IN (G) a[4]  (KP<--)(REP)  =   (R) a[4]  (KP<--)(REP) (by sim and name)
# IN (G) a[3]  (KP<--)(REP)  =   (R) a[3]  (KP<--)(REP) (by sim and name)
# IN (G) a[2]  (KP<--)(REP)  =   (R) a[2]  (KP<--)(REP) (by sim and name)
# IN (G) a[1]  (KP<--)(REP)  =   (R) a[1]  (KP<--)(REP) (by sim and name)
# IN (G) a[0]  (KP<--)(REP)  =   (R) a[0]  (KP<--)(REP) (by sim and name)
# RESOLVED Constraints
# OUT (G) c[7] (REP)  =   (R) c[7] (REP) (by sim and name)
# OUT (G) c[6] (REP)  =   (R) c[6] (REP) (by sim and name)
# OUT (G) c[5] (REP)  =   (R) c[5] (REP) (by sim and name)
# OUT (G) c[4] (REP)  =   (R) c[4] (REP) (by sim and name)
# OUT (G) c[3] (REP)  =   (R) c[3] (REP) (by sim and name)
# OUT (G) c[2] (REP)  =   (R) c[2] (REP) (by sim and name)
# OUT (G) c[1] (REP)  =   (R) c[1] (REP) (by sim and name)
# OUT (G) c[0] (REP)  =   (R) c[0] (REP) (by sim and name)
set_root_module sbox -Golden
set_root_module sbox -Revised
set_module_property -instance {/inst1/s/sub_Bytes[0].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[8].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[16].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[24].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[32].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[40].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[48].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[56].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[64].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[72].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[80].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[88].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[96].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[104].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[112].s} -Golden
set_module_property -instance {/inst1/s/sub_Bytes[120].s} -Golden
set_module_property -instance {/inst1_s_sub_Bytes[0].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[8].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[16].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[24].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[32].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[40].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[48].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[56].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[64].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[72].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[80].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[88].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[96].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[104].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[112].s} -Revised
set_module_property -instance {/inst1_s_sub_Bytes[120].s} -Revised
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -flowgraph -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
add_black_box sbox -module -hier -Golden
add_black_box sbox -module -hier -Revised
usage
# Root Modules
# Comparing
#-------------------------------------------------------------------------------
# MODULE AES_CMAC (G) INSTANCE / (G)
# MODULE AES_CMAC (R) INSTANCE / (R)
# Wrapper size: (G) = 0  (R) = 0
# Periphery size: (G) = 0  (R) = 0
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) clk (REP)  =   (R) clk (REP) (by name)
# IN (G) reset (REP)  =   (R) reset (REP) (by name)
# IN (G) len[15] (REP)  =   (R) len[15] (REP) (by name)
# IN (G) len[14] (REP)  =   (R) len[14] (REP) (by name)
# IN (G) len[13] (REP)  =   (R) len[13] (REP) (by name)
# IN (G) len[12] (REP)  =   (R) len[12] (REP) (by name)
# IN (G) len[11] (REP)  =   (R) len[11] (REP) (by name)
# IN (G) len[10] (REP)  =   (R) len[10] (REP) (by name)
# IN (G) len[9] (REP)  =   (R) len[9] (REP) (by name)
# IN (G) len[8] (REP)  =   (R) len[8] (REP) (by name)
# IN (G) len[7] (REP)  =   (R) len[7] (REP) (by name)
# IN (G) len[6] (REP)  =   (R) len[6] (REP) (by name)
# IN (G) len[5] (REP)  =   (R) len[5] (REP) (by name)
# IN (G) len[4] (REP)  =   (R) len[4] (REP) (by name)
# IN (G) len[3] (REP)  =   (R) len[3] (REP) (by name)
# IN (G) len[2] (REP)  =   (R) len[2] (REP) (by name)
# IN (G) len[1] (REP)  =   (R) len[1] (REP) (by name)
# IN (G) len[0] (REP)  =   (R) len[0] (REP) (by name)
# IN (G) messIn[127] (REP)  =   (R) messIn[127] (REP) (by name)
# IN (G) messIn[126] (REP)  =   (R) messIn[126] (REP) (by name)
# IN (G) messIn[125] (REP)  =   (R) messIn[125] (REP) (by name)
# IN (G) messIn[124] (REP)  =   (R) messIn[124] (REP) (by name)
# IN (G) messIn[123] (REP)  =   (R) messIn[123] (REP) (by name)
# IN (G) messIn[122] (REP)  =   (R) messIn[122] (REP) (by name)
# IN (G) messIn[121] (REP)  =   (R) messIn[121] (REP) (by name)
# IN (G) messIn[120] (REP)  =   (R) messIn[120] (REP) (by name)
# IN (G) messIn[119] (REP)  =   (R) messIn[119] (REP) (by name)
# IN (G) messIn[118] (REP)  =   (R) messIn[118] (REP) (by name)
# IN (G) messIn[117] (REP)  =   (R) messIn[117] (REP) (by name)
# IN (G) messIn[116] (REP)  =   (R) messIn[116] (REP) (by name)
# IN (G) messIn[115] (REP)  =   (R) messIn[115] (REP) (by name)
# IN (G) messIn[114] (REP)  =   (R) messIn[114] (REP) (by name)
# IN (G) messIn[113] (REP)  =   (R) messIn[113] (REP) (by name)
# IN (G) messIn[112] (REP)  =   (R) messIn[112] (REP) (by name)
# IN (G) messIn[111] (REP)  =   (R) messIn[111] (REP) (by name)
# IN (G) messIn[110] (REP)  =   (R) messIn[110] (REP) (by name)
# IN (G) messIn[109] (REP)  =   (R) messIn[109] (REP) (by name)
# IN (G) messIn[108] (REP)  =   (R) messIn[108] (REP) (by name)
# IN (G) messIn[107] (REP)  =   (R) messIn[107] (REP) (by name)
# IN (G) messIn[106] (REP)  =   (R) messIn[106] (REP) (by name)
# IN (G) messIn[105] (REP)  =   (R) messIn[105] (REP) (by name)
# IN (G) messIn[104] (REP)  =   (R) messIn[104] (REP) (by name)
# IN (G) messIn[103] (REP)  =   (R) messIn[103] (REP) (by name)
# IN (G) messIn[102] (REP)  =   (R) messIn[102] (REP) (by name)
# IN (G) messIn[101] (REP)  =   (R) messIn[101] (REP) (by name)
# IN (G) messIn[100] (REP)  =   (R) messIn[100] (REP) (by name)
# IN (G) messIn[99] (REP)  =   (R) messIn[99] (REP) (by name)
# IN (G) messIn[98] (REP)  =   (R) messIn[98] (REP) (by name)
# IN (G) messIn[97] (REP)  =   (R) messIn[97] (REP) (by name)
# IN (G) messIn[96] (REP)  =   (R) messIn[96] (REP) (by name)
# IN (G) messIn[95] (REP)  =   (R) messIn[95] (REP) (by name)
# IN (G) messIn[94] (REP)  =   (R) messIn[94] (REP) (by name)
# IN (G) messIn[93] (REP)  =   (R) messIn[93] (REP) (by name)
# IN (G) messIn[92] (REP)  =   (R) messIn[92] (REP) (by name)
# IN (G) messIn[91] (REP)  =   (R) messIn[91] (REP) (by name)
# IN (G) messIn[90] (REP)  =   (R) messIn[90] (REP) (by name)
# IN (G) messIn[89] (REP)  =   (R) messIn[89] (REP) (by name)
# IN (G) messIn[88] (REP)  =   (R) messIn[88] (REP) (by name)
# IN (G) messIn[87] (REP)  =   (R) messIn[87] (REP) (by name)
# IN (G) messIn[86] (REP)  =   (R) messIn[86] (REP) (by name)
# IN (G) messIn[85] (REP)  =   (R) messIn[85] (REP) (by name)
# IN (G) messIn[84] (REP)  =   (R) messIn[84] (REP) (by name)
# IN (G) messIn[83] (REP)  =   (R) messIn[83] (REP) (by name)
# IN (G) messIn[82] (REP)  =   (R) messIn[82] (REP) (by name)
# IN (G) messIn[81] (REP)  =   (R) messIn[81] (REP) (by name)
# IN (G) messIn[80] (REP)  =   (R) messIn[80] (REP) (by name)
# IN (G) messIn[79] (REP)  =   (R) messIn[79] (REP) (by name)
# IN (G) messIn[78] (REP)  =   (R) messIn[78] (REP) (by name)
# IN (G) messIn[77] (REP)  =   (R) messIn[77] (REP) (by name)
# IN (G) messIn[76] (REP)  =   (R) messIn[76] (REP) (by name)
# IN (G) messIn[75] (REP)  =   (R) messIn[75] (REP) (by name)
# IN (G) messIn[74] (REP)  =   (R) messIn[74] (REP) (by name)
# IN (G) messIn[73] (REP)  =   (R) messIn[73] (REP) (by name)
# IN (G) messIn[72] (REP)  =   (R) messIn[72] (REP) (by name)
# IN (G) messIn[71] (REP)  =   (R) messIn[71] (REP) (by name)
# IN (G) messIn[70] (REP)  =   (R) messIn[70] (REP) (by name)
# IN (G) messIn[69] (REP)  =   (R) messIn[69] (REP) (by name)
# IN (G) messIn[68] (REP)  =   (R) messIn[68] (REP) (by name)
# IN (G) messIn[67] (REP)  =   (R) messIn[67] (REP) (by name)
# IN (G) messIn[66] (REP)  =   (R) messIn[66] (REP) (by name)
# IN (G) messIn[65] (REP)  =   (R) messIn[65] (REP) (by name)
# IN (G) messIn[64] (REP)  =   (R) messIn[64] (REP) (by name)
# IN (G) messIn[63] (REP)  =   (R) messIn[63] (REP) (by name)
# IN (G) messIn[62] (REP)  =   (R) messIn[62] (REP) (by name)
# IN (G) messIn[61] (REP)  =   (R) messIn[61] (REP) (by name)
# IN (G) messIn[60] (REP)  =   (R) messIn[60] (REP) (by name)
# IN (G) messIn[59] (REP)  =   (R) messIn[59] (REP) (by name)
# IN (G) messIn[58] (REP)  =   (R) messIn[58] (REP) (by name)
# IN (G) messIn[57] (REP)  =   (R) messIn[57] (REP) (by name)
# IN (G) messIn[56] (REP)  =   (R) messIn[56] (REP) (by name)
# IN (G) messIn[55] (REP)  =   (R) messIn[55] (REP) (by name)
# IN (G) messIn[54] (REP)  =   (R) messIn[54] (REP) (by name)
# IN (G) messIn[53] (REP)  =   (R) messIn[53] (REP) (by name)
# IN (G) messIn[52] (REP)  =   (R) messIn[52] (REP) (by name)
# IN (G) messIn[51] (REP)  =   (R) messIn[51] (REP) (by name)
# IN (G) messIn[50] (REP)  =   (R) messIn[50] (REP) (by name)
# IN (G) messIn[49] (REP)  =   (R) messIn[49] (REP) (by name)
# IN (G) messIn[48] (REP)  =   (R) messIn[48] (REP) (by name)
# IN (G) messIn[47] (REP)  =   (R) messIn[47] (REP) (by name)
# IN (G) messIn[46] (REP)  =   (R) messIn[46] (REP) (by name)
# IN (G) messIn[45] (REP)  =   (R) messIn[45] (REP) (by name)
# IN (G) messIn[44] (REP)  =   (R) messIn[44] (REP) (by name)
# IN (G) messIn[43] (REP)  =   (R) messIn[43] (REP) (by name)
# IN (G) messIn[42] (REP)  =   (R) messIn[42] (REP) (by name)
# IN (G) messIn[41] (REP)  =   (R) messIn[41] (REP) (by name)
# IN (G) messIn[40] (REP)  =   (R) messIn[40] (REP) (by name)
# IN (G) messIn[39] (REP)  =   (R) messIn[39] (REP) (by name)
# IN (G) messIn[38] (REP)  =   (R) messIn[38] (REP) (by name)
# IN (G) messIn[37] (REP)  =   (R) messIn[37] (REP) (by name)
# IN (G) messIn[36] (REP)  =   (R) messIn[36] (REP) (by name)
# IN (G) messIn[35] (REP)  =   (R) messIn[35] (REP) (by name)
# IN (G) messIn[34] (REP)  =   (R) messIn[34] (REP) (by name)
# IN (G) messIn[33] (REP)  =   (R) messIn[33] (REP) (by name)
# IN (G) messIn[32] (REP)  =   (R) messIn[32] (REP) (by name)
# IN (G) messIn[31] (REP)  =   (R) messIn[31] (REP) (by name)
# IN (G) messIn[30] (REP)  =   (R) messIn[30] (REP) (by name)
# IN (G) messIn[29] (REP)  =   (R) messIn[29] (REP) (by name)
# IN (G) messIn[28] (REP)  =   (R) messIn[28] (REP) (by name)
# IN (G) messIn[27] (REP)  =   (R) messIn[27] (REP) (by name)
# IN (G) messIn[26] (REP)  =   (R) messIn[26] (REP) (by name)
# IN (G) messIn[25] (REP)  =   (R) messIn[25] (REP) (by name)
# IN (G) messIn[24] (REP)  =   (R) messIn[24] (REP) (by name)
# IN (G) messIn[23] (REP)  =   (R) messIn[23] (REP) (by name)
# IN (G) messIn[22] (REP)  =   (R) messIn[22] (REP) (by name)
# IN (G) messIn[21] (REP)  =   (R) messIn[21] (REP) (by name)
# IN (G) messIn[20] (REP)  =   (R) messIn[20] (REP) (by name)
# IN (G) messIn[19] (REP)  =   (R) messIn[19] (REP) (by name)
# IN (G) messIn[18] (REP)  =   (R) messIn[18] (REP) (by name)
# IN (G) messIn[17] (REP)  =   (R) messIn[17] (REP) (by name)
# IN (G) messIn[16] (REP)  =   (R) messIn[16] (REP) (by name)
# IN (G) messIn[15] (REP)  =   (R) messIn[15] (REP) (by name)
# IN (G) messIn[14] (REP)  =   (R) messIn[14] (REP) (by name)
# IN (G) messIn[13] (REP)  =   (R) messIn[13] (REP) (by name)
# IN (G) messIn[12] (REP)  =   (R) messIn[12] (REP) (by name)
# IN (G) messIn[11] (REP)  =   (R) messIn[11] (REP) (by name)
# IN (G) messIn[10] (REP)  =   (R) messIn[10] (REP) (by name)
# IN (G) messIn[9] (REP)  =   (R) messIn[9] (REP) (by name)
# IN (G) messIn[8] (REP)  =   (R) messIn[8] (REP) (by name)
# IN (G) messIn[7] (REP)  =   (R) messIn[7] (REP) (by name)
# IN (G) messIn[6] (REP)  =   (R) messIn[6] (REP) (by name)
# IN (G) messIn[5] (REP)  =   (R) messIn[5] (REP) (by name)
# IN (G) messIn[4] (REP)  =   (R) messIn[4] (REP) (by name)
# IN (G) messIn[3] (REP)  =   (R) messIn[3] (REP) (by name)
# IN (G) messIn[2] (REP)  =   (R) messIn[2] (REP) (by name)
# IN (G) messIn[1] (REP)  =   (R) messIn[1] (REP) (by name)
# IN (G) messIn[0] (REP)  =   (R) messIn[0] (REP) (by name)
# IN (G) cmacIn[127] (REP)  =   (R) cmacIn[127] (REP) (by name)
# IN (G) cmacIn[126] (REP)  =   (R) cmacIn[126] (REP) (by name)
# IN (G) cmacIn[125] (REP)  =   (R) cmacIn[125] (REP) (by name)
# IN (G) cmacIn[124] (REP)  =   (R) cmacIn[124] (REP) (by name)
# IN (G) cmacIn[123] (REP)  =   (R) cmacIn[123] (REP) (by name)
# IN (G) cmacIn[122] (REP)  =   (R) cmacIn[122] (REP) (by name)
# IN (G) cmacIn[121] (REP)  =   (R) cmacIn[121] (REP) (by name)
# IN (G) cmacIn[120] (REP)  =   (R) cmacIn[120] (REP) (by name)
# IN (G) cmacIn[119] (REP)  =   (R) cmacIn[119] (REP) (by name)
# IN (G) cmacIn[118] (REP)  =   (R) cmacIn[118] (REP) (by name)
# IN (G) cmacIn[117] (REP)  =   (R) cmacIn[117] (REP) (by name)
# IN (G) cmacIn[116] (REP)  =   (R) cmacIn[116] (REP) (by name)
# IN (G) cmacIn[115] (REP)  =   (R) cmacIn[115] (REP) (by name)
# IN (G) cmacIn[114] (REP)  =   (R) cmacIn[114] (REP) (by name)
# IN (G) cmacIn[113] (REP)  =   (R) cmacIn[113] (REP) (by name)
# IN (G) cmacIn[112] (REP)  =   (R) cmacIn[112] (REP) (by name)
# IN (G) cmacIn[111] (REP)  =   (R) cmacIn[111] (REP) (by name)
# IN (G) cmacIn[110] (REP)  =   (R) cmacIn[110] (REP) (by name)
# IN (G) cmacIn[109] (REP)  =   (R) cmacIn[109] (REP) (by name)
# IN (G) cmacIn[108] (REP)  =   (R) cmacIn[108] (REP) (by name)
# IN (G) cmacIn[107] (REP)  =   (R) cmacIn[107] (REP) (by name)
# IN (G) cmacIn[106] (REP)  =   (R) cmacIn[106] (REP) (by name)
# IN (G) cmacIn[105] (REP)  =   (R) cmacIn[105] (REP) (by name)
# IN (G) cmacIn[104] (REP)  =   (R) cmacIn[104] (REP) (by name)
# IN (G) cmacIn[103] (REP)  =   (R) cmacIn[103] (REP) (by name)
# IN (G) cmacIn[102] (REP)  =   (R) cmacIn[102] (REP) (by name)
# IN (G) cmacIn[101] (REP)  =   (R) cmacIn[101] (REP) (by name)
# IN (G) cmacIn[100] (REP)  =   (R) cmacIn[100] (REP) (by name)
# IN (G) cmacIn[99] (REP)  =   (R) cmacIn[99] (REP) (by name)
# IN (G) cmacIn[98] (REP)  =   (R) cmacIn[98] (REP) (by name)
# IN (G) cmacIn[97] (REP)  =   (R) cmacIn[97] (REP) (by name)
# IN (G) cmacIn[96] (REP)  =   (R) cmacIn[96] (REP) (by name)
# IN (G) cmacIn[95] (REP)  =   (R) cmacIn[95] (REP) (by name)
# IN (G) cmacIn[94] (REP)  =   (R) cmacIn[94] (REP) (by name)
# IN (G) cmacIn[93] (REP)  =   (R) cmacIn[93] (REP) (by name)
# IN (G) cmacIn[92] (REP)  =   (R) cmacIn[92] (REP) (by name)
# IN (G) cmacIn[91] (REP)  =   (R) cmacIn[91] (REP) (by name)
# IN (G) cmacIn[90] (REP)  =   (R) cmacIn[90] (REP) (by name)
# IN (G) cmacIn[89] (REP)  =   (R) cmacIn[89] (REP) (by name)
# IN (G) cmacIn[88] (REP)  =   (R) cmacIn[88] (REP) (by name)
# IN (G) cmacIn[87] (REP)  =   (R) cmacIn[87] (REP) (by name)
# IN (G) cmacIn[86] (REP)  =   (R) cmacIn[86] (REP) (by name)
# IN (G) cmacIn[85] (REP)  =   (R) cmacIn[85] (REP) (by name)
# IN (G) cmacIn[84] (REP)  =   (R) cmacIn[84] (REP) (by name)
# IN (G) cmacIn[83] (REP)  =   (R) cmacIn[83] (REP) (by name)
# IN (G) cmacIn[82] (REP)  =   (R) cmacIn[82] (REP) (by name)
# IN (G) cmacIn[81] (REP)  =   (R) cmacIn[81] (REP) (by name)
# IN (G) cmacIn[80] (REP)  =   (R) cmacIn[80] (REP) (by name)
# IN (G) cmacIn[79] (REP)  =   (R) cmacIn[79] (REP) (by name)
# IN (G) cmacIn[78] (REP)  =   (R) cmacIn[78] (REP) (by name)
# IN (G) cmacIn[77] (REP)  =   (R) cmacIn[77] (REP) (by name)
# IN (G) cmacIn[76] (REP)  =   (R) cmacIn[76] (REP) (by name)
# IN (G) cmacIn[75] (REP)  =   (R) cmacIn[75] (REP) (by name)
# IN (G) cmacIn[74] (REP)  =   (R) cmacIn[74] (REP) (by name)
# IN (G) cmacIn[73] (REP)  =   (R) cmacIn[73] (REP) (by name)
# IN (G) cmacIn[72] (REP)  =   (R) cmacIn[72] (REP) (by name)
# IN (G) cmacIn[71] (REP)  =   (R) cmacIn[71] (REP) (by name)
# IN (G) cmacIn[70] (REP)  =   (R) cmacIn[70] (REP) (by name)
# IN (G) cmacIn[69] (REP)  =   (R) cmacIn[69] (REP) (by name)
# IN (G) cmacIn[68] (REP)  =   (R) cmacIn[68] (REP) (by name)
# IN (G) cmacIn[67] (REP)  =   (R) cmacIn[67] (REP) (by name)
# IN (G) cmacIn[66] (REP)  =   (R) cmacIn[66] (REP) (by name)
# IN (G) cmacIn[65] (REP)  =   (R) cmacIn[65] (REP) (by name)
# IN (G) cmacIn[64] (REP)  =   (R) cmacIn[64] (REP) (by name)
# IN (G) cmacIn[63] (REP)  =   (R) cmacIn[63] (REP) (by name)
# IN (G) cmacIn[62] (REP)  =   (R) cmacIn[62] (REP) (by name)
# IN (G) cmacIn[61] (REP)  =   (R) cmacIn[61] (REP) (by name)
# IN (G) cmacIn[60] (REP)  =   (R) cmacIn[60] (REP) (by name)
# IN (G) cmacIn[59] (REP)  =   (R) cmacIn[59] (REP) (by name)
# IN (G) cmacIn[58] (REP)  =   (R) cmacIn[58] (REP) (by name)
# IN (G) cmacIn[57] (REP)  =   (R) cmacIn[57] (REP) (by name)
# IN (G) cmacIn[56] (REP)  =   (R) cmacIn[56] (REP) (by name)
# IN (G) cmacIn[55] (REP)  =   (R) cmacIn[55] (REP) (by name)
# IN (G) cmacIn[54] (REP)  =   (R) cmacIn[54] (REP) (by name)
# IN (G) cmacIn[53] (REP)  =   (R) cmacIn[53] (REP) (by name)
# IN (G) cmacIn[52] (REP)  =   (R) cmacIn[52] (REP) (by name)
# IN (G) cmacIn[51] (REP)  =   (R) cmacIn[51] (REP) (by name)
# IN (G) cmacIn[50] (REP)  =   (R) cmacIn[50] (REP) (by name)
# IN (G) cmacIn[49] (REP)  =   (R) cmacIn[49] (REP) (by name)
# IN (G) cmacIn[48] (REP)  =   (R) cmacIn[48] (REP) (by name)
# IN (G) cmacIn[47] (REP)  =   (R) cmacIn[47] (REP) (by name)
# IN (G) cmacIn[46] (REP)  =   (R) cmacIn[46] (REP) (by name)
# IN (G) cmacIn[45] (REP)  =   (R) cmacIn[45] (REP) (by name)
# IN (G) cmacIn[44] (REP)  =   (R) cmacIn[44] (REP) (by name)
# IN (G) cmacIn[43] (REP)  =   (R) cmacIn[43] (REP) (by name)
# IN (G) cmacIn[42] (REP)  =   (R) cmacIn[42] (REP) (by name)
# IN (G) cmacIn[41] (REP)  =   (R) cmacIn[41] (REP) (by name)
# IN (G) cmacIn[40] (REP)  =   (R) cmacIn[40] (REP) (by name)
# IN (G) cmacIn[39] (REP)  =   (R) cmacIn[39] (REP) (by name)
# IN (G) cmacIn[38] (REP)  =   (R) cmacIn[38] (REP) (by name)
# IN (G) cmacIn[37] (REP)  =   (R) cmacIn[37] (REP) (by name)
# IN (G) cmacIn[36] (REP)  =   (R) cmacIn[36] (REP) (by name)
# IN (G) cmacIn[35] (REP)  =   (R) cmacIn[35] (REP) (by name)
# IN (G) cmacIn[34] (REP)  =   (R) cmacIn[34] (REP) (by name)
# IN (G) cmacIn[33] (REP)  =   (R) cmacIn[33] (REP) (by name)
# IN (G) cmacIn[32] (REP)  =   (R) cmacIn[32] (REP) (by name)
# IN (G) cmacIn[31] (REP)  =   (R) cmacIn[31] (REP) (by name)
# IN (G) cmacIn[30] (REP)  =   (R) cmacIn[30] (REP) (by name)
# IN (G) cmacIn[29] (REP)  =   (R) cmacIn[29] (REP) (by name)
# IN (G) cmacIn[28] (REP)  =   (R) cmacIn[28] (REP) (by name)
# IN (G) cmacIn[27] (REP)  =   (R) cmacIn[27] (REP) (by name)
# IN (G) cmacIn[26] (REP)  =   (R) cmacIn[26] (REP) (by name)
# IN (G) cmacIn[25] (REP)  =   (R) cmacIn[25] (REP) (by name)
# IN (G) cmacIn[24] (REP)  =   (R) cmacIn[24] (REP) (by name)
# IN (G) cmacIn[23] (REP)  =   (R) cmacIn[23] (REP) (by name)
# IN (G) cmacIn[22] (REP)  =   (R) cmacIn[22] (REP) (by name)
# IN (G) cmacIn[21] (REP)  =   (R) cmacIn[21] (REP) (by name)
# IN (G) cmacIn[20] (REP)  =   (R) cmacIn[20] (REP) (by name)
# IN (G) cmacIn[19] (REP)  =   (R) cmacIn[19] (REP) (by name)
# IN (G) cmacIn[18] (REP)  =   (R) cmacIn[18] (REP) (by name)
# IN (G) cmacIn[17] (REP)  =   (R) cmacIn[17] (REP) (by name)
# IN (G) cmacIn[16] (REP)  =   (R) cmacIn[16] (REP) (by name)
# IN (G) cmacIn[15] (REP)  =   (R) cmacIn[15] (REP) (by name)
# IN (G) cmacIn[14] (REP)  =   (R) cmacIn[14] (REP) (by name)
# IN (G) cmacIn[13] (REP)  =   (R) cmacIn[13] (REP) (by name)
# IN (G) cmacIn[12] (REP)  =   (R) cmacIn[12] (REP) (by name)
# IN (G) cmacIn[11] (REP)  =   (R) cmacIn[11] (REP) (by name)
# IN (G) cmacIn[10] (REP)  =   (R) cmacIn[10] (REP) (by name)
# IN (G) cmacIn[9] (REP)  =   (R) cmacIn[9] (REP) (by name)
# IN (G) cmacIn[8] (REP)  =   (R) cmacIn[8] (REP) (by name)
# IN (G) cmacIn[7] (REP)  =   (R) cmacIn[7] (REP) (by name)
# IN (G) cmacIn[6] (REP)  =   (R) cmacIn[6] (REP) (by name)
# IN (G) cmacIn[5] (REP)  =   (R) cmacIn[5] (REP) (by name)
# IN (G) cmacIn[4] (REP)  =   (R) cmacIn[4] (REP) (by name)
# IN (G) cmacIn[3] (REP)  =   (R) cmacIn[3] (REP) (by name)
# IN (G) cmacIn[2] (REP)  =   (R) cmacIn[2] (REP) (by name)
# IN (G) cmacIn[1] (REP)  =   (R) cmacIn[1] (REP) (by name)
# IN (G) cmacIn[0] (REP)  =   (R) cmacIn[0] (REP) (by name)
# RESOLVED Constraints
# OUT (G) encrypted[127] (REP)  =   (R) encrypted[127] (REP) (by name)
# OUT (G) encrypted[126] (REP)  =   (R) encrypted[126] (REP) (by name)
# OUT (G) encrypted[125] (REP)  =   (R) encrypted[125] (REP) (by name)
# OUT (G) encrypted[124] (REP)  =   (R) encrypted[124] (REP) (by name)
# OUT (G) encrypted[123] (REP)  =   (R) encrypted[123] (REP) (by name)
# OUT (G) encrypted[122] (REP)  =   (R) encrypted[122] (REP) (by name)
# OUT (G) encrypted[121] (REP)  =   (R) encrypted[121] (REP) (by name)
# OUT (G) encrypted[120] (REP)  =   (R) encrypted[120] (REP) (by name)
# OUT (G) encrypted[119] (REP)  =   (R) encrypted[119] (REP) (by name)
# OUT (G) encrypted[118] (REP)  =   (R) encrypted[118] (REP) (by name)
# OUT (G) encrypted[117] (REP)  =   (R) encrypted[117] (REP) (by name)
# OUT (G) encrypted[116] (REP)  =   (R) encrypted[116] (REP) (by name)
# OUT (G) encrypted[115] (REP)  =   (R) encrypted[115] (REP) (by name)
# OUT (G) encrypted[114] (REP)  =   (R) encrypted[114] (REP) (by name)
# OUT (G) encrypted[113] (REP)  =   (R) encrypted[113] (REP) (by name)
# OUT (G) encrypted[112] (REP)  =   (R) encrypted[112] (REP) (by name)
# OUT (G) encrypted[111] (REP)  =   (R) encrypted[111] (REP) (by name)
# OUT (G) encrypted[110] (REP)  =   (R) encrypted[110] (REP) (by name)
# OUT (G) encrypted[109] (REP)  =   (R) encrypted[109] (REP) (by name)
# OUT (G) encrypted[108] (REP)  =   (R) encrypted[108] (REP) (by name)
# OUT (G) encrypted[107] (REP)  =   (R) encrypted[107] (REP) (by name)
# OUT (G) encrypted[106] (REP)  =   (R) encrypted[106] (REP) (by name)
# OUT (G) encrypted[105] (REP)  =   (R) encrypted[105] (REP) (by name)
# OUT (G) encrypted[104] (REP)  =   (R) encrypted[104] (REP) (by name)
# OUT (G) encrypted[103] (REP)  =   (R) encrypted[103] (REP) (by name)
# OUT (G) encrypted[102] (REP)  =   (R) encrypted[102] (REP) (by name)
# OUT (G) encrypted[101] (REP)  =   (R) encrypted[101] (REP) (by name)
# OUT (G) encrypted[100] (REP)  =   (R) encrypted[100] (REP) (by name)
# OUT (G) encrypted[99] (REP)  =   (R) encrypted[99] (REP) (by name)
# OUT (G) encrypted[98] (REP)  =   (R) encrypted[98] (REP) (by name)
# OUT (G) encrypted[97] (REP)  =   (R) encrypted[97] (REP) (by name)
# OUT (G) encrypted[96] (REP)  =   (R) encrypted[96] (REP) (by name)
# OUT (G) encrypted[95] (REP)  =   (R) encrypted[95] (REP) (by name)
# OUT (G) encrypted[94] (REP)  =   (R) encrypted[94] (REP) (by name)
# OUT (G) encrypted[93] (REP)  =   (R) encrypted[93] (REP) (by name)
# OUT (G) encrypted[92] (REP)  =   (R) encrypted[92] (REP) (by name)
# OUT (G) encrypted[91] (REP)  =   (R) encrypted[91] (REP) (by name)
# OUT (G) encrypted[90] (REP)  =   (R) encrypted[90] (REP) (by name)
# OUT (G) encrypted[89] (REP)  =   (R) encrypted[89] (REP) (by name)
# OUT (G) encrypted[88] (REP)  =   (R) encrypted[88] (REP) (by name)
# OUT (G) encrypted[87] (REP)  =   (R) encrypted[87] (REP) (by name)
# OUT (G) encrypted[86] (REP)  =   (R) encrypted[86] (REP) (by name)
# OUT (G) encrypted[85] (REP)  =   (R) encrypted[85] (REP) (by name)
# OUT (G) encrypted[84] (REP)  =   (R) encrypted[84] (REP) (by name)
# OUT (G) encrypted[83] (REP)  =   (R) encrypted[83] (REP) (by name)
# OUT (G) encrypted[82] (REP)  =   (R) encrypted[82] (REP) (by name)
# OUT (G) encrypted[81] (REP)  =   (R) encrypted[81] (REP) (by name)
# OUT (G) encrypted[80] (REP)  =   (R) encrypted[80] (REP) (by name)
# OUT (G) encrypted[79] (REP)  =   (R) encrypted[79] (REP) (by name)
# OUT (G) encrypted[78] (REP)  =   (R) encrypted[78] (REP) (by name)
# OUT (G) encrypted[77] (REP)  =   (R) encrypted[77] (REP) (by name)
# OUT (G) encrypted[76] (REP)  =   (R) encrypted[76] (REP) (by name)
# OUT (G) encrypted[75] (REP)  =   (R) encrypted[75] (REP) (by name)
# OUT (G) encrypted[74] (REP)  =   (R) encrypted[74] (REP) (by name)
# OUT (G) encrypted[73] (REP)  =   (R) encrypted[73] (REP) (by name)
# OUT (G) encrypted[72] (REP)  =   (R) encrypted[72] (REP) (by name)
# OUT (G) encrypted[71] (REP)  =   (R) encrypted[71] (REP) (by name)
# OUT (G) encrypted[70] (REP)  =   (R) encrypted[70] (REP) (by name)
# OUT (G) encrypted[69] (REP)  =   (R) encrypted[69] (REP) (by name)
# OUT (G) encrypted[68] (REP)  =   (R) encrypted[68] (REP) (by name)
# OUT (G) encrypted[67] (REP)  =   (R) encrypted[67] (REP) (by name)
# OUT (G) encrypted[66] (REP)  =   (R) encrypted[66] (REP) (by name)
# OUT (G) encrypted[65] (REP)  =   (R) encrypted[65] (REP) (by name)
# OUT (G) encrypted[64] (REP)  =   (R) encrypted[64] (REP) (by name)
# OUT (G) encrypted[63] (REP)  =   (R) encrypted[63] (REP) (by name)
# OUT (G) encrypted[62] (REP)  =   (R) encrypted[62] (REP) (by name)
# OUT (G) encrypted[61] (REP)  =   (R) encrypted[61] (REP) (by name)
# OUT (G) encrypted[60] (REP)  =   (R) encrypted[60] (REP) (by name)
# OUT (G) encrypted[59] (REP)  =   (R) encrypted[59] (REP) (by name)
# OUT (G) encrypted[58] (REP)  =   (R) encrypted[58] (REP) (by name)
# OUT (G) encrypted[57] (REP)  =   (R) encrypted[57] (REP) (by name)
# OUT (G) encrypted[56] (REP)  =   (R) encrypted[56] (REP) (by name)
# OUT (G) encrypted[55] (REP)  =   (R) encrypted[55] (REP) (by name)
# OUT (G) encrypted[54] (REP)  =   (R) encrypted[54] (REP) (by name)
# OUT (G) encrypted[53] (REP)  =   (R) encrypted[53] (REP) (by name)
# OUT (G) encrypted[52] (REP)  =   (R) encrypted[52] (REP) (by name)
# OUT (G) encrypted[51] (REP)  =   (R) encrypted[51] (REP) (by name)
# OUT (G) encrypted[50] (REP)  =   (R) encrypted[50] (REP) (by name)
# OUT (G) encrypted[49] (REP)  =   (R) encrypted[49] (REP) (by name)
# OUT (G) encrypted[48] (REP)  =   (R) encrypted[48] (REP) (by name)
# OUT (G) encrypted[47] (REP)  =   (R) encrypted[47] (REP) (by name)
# OUT (G) encrypted[46] (REP)  =   (R) encrypted[46] (REP) (by name)
# OUT (G) encrypted[45] (REP)  =   (R) encrypted[45] (REP) (by name)
# OUT (G) encrypted[44] (REP)  =   (R) encrypted[44] (REP) (by name)
# OUT (G) encrypted[43] (REP)  =   (R) encrypted[43] (REP) (by name)
# OUT (G) encrypted[42] (REP)  =   (R) encrypted[42] (REP) (by name)
# OUT (G) encrypted[41] (REP)  =   (R) encrypted[41] (REP) (by name)
# OUT (G) encrypted[40] (REP)  =   (R) encrypted[40] (REP) (by name)
# OUT (G) encrypted[39] (REP)  =   (R) encrypted[39] (REP) (by name)
# OUT (G) encrypted[38] (REP)  =   (R) encrypted[38] (REP) (by name)
# OUT (G) encrypted[37] (REP)  =   (R) encrypted[37] (REP) (by name)
# OUT (G) encrypted[36] (REP)  =   (R) encrypted[36] (REP) (by name)
# OUT (G) encrypted[35] (REP)  =   (R) encrypted[35] (REP) (by name)
# OUT (G) encrypted[34] (REP)  =   (R) encrypted[34] (REP) (by name)
# OUT (G) encrypted[33] (REP)  =   (R) encrypted[33] (REP) (by name)
# OUT (G) encrypted[32] (REP)  =   (R) encrypted[32] (REP) (by name)
# OUT (G) encrypted[31] (REP)  =   (R) encrypted[31] (REP) (by name)
# OUT (G) encrypted[30] (REP)  =   (R) encrypted[30] (REP) (by name)
# OUT (G) encrypted[29] (REP)  =   (R) encrypted[29] (REP) (by name)
# OUT (G) encrypted[28] (REP)  =   (R) encrypted[28] (REP) (by name)
# OUT (G) encrypted[27] (REP)  =   (R) encrypted[27] (REP) (by name)
# OUT (G) encrypted[26] (REP)  =   (R) encrypted[26] (REP) (by name)
# OUT (G) encrypted[25] (REP)  =   (R) encrypted[25] (REP) (by name)
# OUT (G) encrypted[24] (REP)  =   (R) encrypted[24] (REP) (by name)
# OUT (G) encrypted[23] (REP)  =   (R) encrypted[23] (REP) (by name)
# OUT (G) encrypted[22] (REP)  =   (R) encrypted[22] (REP) (by name)
# OUT (G) encrypted[21] (REP)  =   (R) encrypted[21] (REP) (by name)
# OUT (G) encrypted[20] (REP)  =   (R) encrypted[20] (REP) (by name)
# OUT (G) encrypted[19] (REP)  =   (R) encrypted[19] (REP) (by name)
# OUT (G) encrypted[18] (REP)  =   (R) encrypted[18] (REP) (by name)
# OUT (G) encrypted[17] (REP)  =   (R) encrypted[17] (REP) (by name)
# OUT (G) encrypted[16] (REP)  =   (R) encrypted[16] (REP) (by name)
# OUT (G) encrypted[15] (REP)  =   (R) encrypted[15] (REP) (by name)
# OUT (G) encrypted[14] (REP)  =   (R) encrypted[14] (REP) (by name)
# OUT (G) encrypted[13] (REP)  =   (R) encrypted[13] (REP) (by name)
# OUT (G) encrypted[12] (REP)  =   (R) encrypted[12] (REP) (by name)
# OUT (G) encrypted[11] (REP)  =   (R) encrypted[11] (REP) (by name)
# OUT (G) encrypted[10] (REP)  =   (R) encrypted[10] (REP) (by name)
# OUT (G) encrypted[9] (REP)  =   (R) encrypted[9] (REP) (by name)
# OUT (G) encrypted[8] (REP)  =   (R) encrypted[8] (REP) (by name)
# OUT (G) encrypted[7] (REP)  =   (R) encrypted[7] (REP) (by name)
# OUT (G) encrypted[6] (REP)  =   (R) encrypted[6] (REP) (by name)
# OUT (G) encrypted[5] (REP)  =   (R) encrypted[5] (REP) (by name)
# OUT (G) encrypted[4] (REP)  =   (R) encrypted[4] (REP) (by name)
# OUT (G) encrypted[3] (REP)  =   (R) encrypted[3] (REP) (by name)
# OUT (G) encrypted[2] (REP)  =   (R) encrypted[2] (REP) (by name)
# OUT (G) encrypted[1] (REP)  =   (R) encrypted[1] (REP) (by name)
# OUT (G) encrypted[0] (REP)  =   (R) encrypted[0] (REP) (by name)
# OUT (G) cmacDone (REP)  =   (R) cmacDone (REP) (by name)
# OUT (G) messAddra[8] (REP)  =   (R) messAddra[8] (REP) (by name)
# OUT (G) messAddra[7] (REP)  =   (R) messAddra[7] (REP) (by name)
# OUT (G) messAddra[6] (REP)  =   (R) messAddra[6] (REP) (by name)
# OUT (G) messAddra[5] (REP)  =   (R) messAddra[5] (REP) (by name)
# OUT (G) messAddra[4] (REP)  =   (R) messAddra[4] (REP) (by name)
# OUT (G) messAddra[3] (REP)  =   (R) messAddra[3] (REP) (by name)
# OUT (G) messAddra[2] (REP)  =   (R) messAddra[2] (REP) (by name)
# OUT (G) messAddra[1] (REP)  =   (R) messAddra[1] (REP) (by name)
# OUT (G) messAddra[0] (REP)  =   (R) messAddra[0] (REP) (by name)
# OUT (G) cmacAddra[8] (REP)  =   (R) cmacAddra[8] (REP) (by name)
# OUT (G) cmacAddra[7] (REP)  =   (R) cmacAddra[7] (REP) (by name)
# OUT (G) cmacAddra[6] (REP)  =   (R) cmacAddra[6] (REP) (by name)
# OUT (G) cmacAddra[5] (REP)  =   (R) cmacAddra[5] (REP) (by name)
# OUT (G) cmacAddra[4] (REP)  =   (R) cmacAddra[4] (REP) (by name)
# OUT (G) cmacAddra[3] (REP)  =   (R) cmacAddra[3] (REP) (by name)
# OUT (G) cmacAddra[2] (REP)  =   (R) cmacAddra[2] (REP) (by name)
# OUT (G) cmacAddra[1] (REP)  =   (R) cmacAddra[1] (REP) (by name)
# OUT (G) cmacAddra[0] (REP)  =   (R) cmacAddra[0] (REP) (by name)
# OUT (G) tag[127] (REP)  =   (R) tag[127] (REP) (by name)
# OUT (G) tag[126] (REP)  =   (R) tag[126] (REP) (by name)
# OUT (G) tag[125] (REP)  =   (R) tag[125] (REP) (by name)
# OUT (G) tag[124] (REP)  =   (R) tag[124] (REP) (by name)
# OUT (G) tag[123] (REP)  =   (R) tag[123] (REP) (by name)
# OUT (G) tag[122] (REP)  =   (R) tag[122] (REP) (by name)
# OUT (G) tag[121] (REP)  =   (R) tag[121] (REP) (by name)
# OUT (G) tag[120] (REP)  =   (R) tag[120] (REP) (by name)
# OUT (G) tag[119] (REP)  =   (R) tag[119] (REP) (by name)
# OUT (G) tag[118] (REP)  =   (R) tag[118] (REP) (by name)
# OUT (G) tag[117] (REP)  =   (R) tag[117] (REP) (by name)
# OUT (G) tag[116] (REP)  =   (R) tag[116] (REP) (by name)
# OUT (G) tag[115] (REP)  =   (R) tag[115] (REP) (by name)
# OUT (G) tag[114] (REP)  =   (R) tag[114] (REP) (by name)
# OUT (G) tag[113] (REP)  =   (R) tag[113] (REP) (by name)
# OUT (G) tag[112] (REP)  =   (R) tag[112] (REP) (by name)
# OUT (G) tag[111] (REP)  =   (R) tag[111] (REP) (by name)
# OUT (G) tag[110] (REP)  =   (R) tag[110] (REP) (by name)
# OUT (G) tag[109] (REP)  =   (R) tag[109] (REP) (by name)
# OUT (G) tag[108] (REP)  =   (R) tag[108] (REP) (by name)
# OUT (G) tag[107] (REP)  =   (R) tag[107] (REP) (by name)
# OUT (G) tag[106] (REP)  =   (R) tag[106] (REP) (by name)
# OUT (G) tag[105] (REP)  =   (R) tag[105] (REP) (by name)
# OUT (G) tag[104] (REP)  =   (R) tag[104] (REP) (by name)
# OUT (G) tag[103] (REP)  =   (R) tag[103] (REP) (by name)
# OUT (G) tag[102] (REP)  =   (R) tag[102] (REP) (by name)
# OUT (G) tag[101] (REP)  =   (R) tag[101] (REP) (by name)
# OUT (G) tag[100] (REP)  =   (R) tag[100] (REP) (by name)
# OUT (G) tag[99] (REP)  =   (R) tag[99] (REP) (by name)
# OUT (G) tag[98] (REP)  =   (R) tag[98] (REP) (by name)
# OUT (G) tag[97] (REP)  =   (R) tag[97] (REP) (by name)
# OUT (G) tag[96] (REP)  =   (R) tag[96] (REP) (by name)
# OUT (G) tag[95] (REP)  =   (R) tag[95] (REP) (by name)
# OUT (G) tag[94] (REP)  =   (R) tag[94] (REP) (by name)
# OUT (G) tag[93] (REP)  =   (R) tag[93] (REP) (by name)
# OUT (G) tag[92] (REP)  =   (R) tag[92] (REP) (by name)
# OUT (G) tag[91] (REP)  =   (R) tag[91] (REP) (by name)
# OUT (G) tag[90] (REP)  =   (R) tag[90] (REP) (by name)
# OUT (G) tag[89] (REP)  =   (R) tag[89] (REP) (by name)
# OUT (G) tag[88] (REP)  =   (R) tag[88] (REP) (by name)
# OUT (G) tag[87] (REP)  =   (R) tag[87] (REP) (by name)
# OUT (G) tag[86] (REP)  =   (R) tag[86] (REP) (by name)
# OUT (G) tag[85] (REP)  =   (R) tag[85] (REP) (by name)
# OUT (G) tag[84] (REP)  =   (R) tag[84] (REP) (by name)
# OUT (G) tag[83] (REP)  =   (R) tag[83] (REP) (by name)
# OUT (G) tag[82] (REP)  =   (R) tag[82] (REP) (by name)
# OUT (G) tag[81] (REP)  =   (R) tag[81] (REP) (by name)
# OUT (G) tag[80] (REP)  =   (R) tag[80] (REP) (by name)
# OUT (G) tag[79] (REP)  =   (R) tag[79] (REP) (by name)
# OUT (G) tag[78] (REP)  =   (R) tag[78] (REP) (by name)
# OUT (G) tag[77] (REP)  =   (R) tag[77] (REP) (by name)
# OUT (G) tag[76] (REP)  =   (R) tag[76] (REP) (by name)
# OUT (G) tag[75] (REP)  =   (R) tag[75] (REP) (by name)
# OUT (G) tag[74] (REP)  =   (R) tag[74] (REP) (by name)
# OUT (G) tag[73] (REP)  =   (R) tag[73] (REP) (by name)
# OUT (G) tag[72] (REP)  =   (R) tag[72] (REP) (by name)
# OUT (G) tag[71] (REP)  =   (R) tag[71] (REP) (by name)
# OUT (G) tag[70] (REP)  =   (R) tag[70] (REP) (by name)
# OUT (G) tag[69] (REP)  =   (R) tag[69] (REP) (by name)
# OUT (G) tag[68] (REP)  =   (R) tag[68] (REP) (by name)
# OUT (G) tag[67] (REP)  =   (R) tag[67] (REP) (by name)
# OUT (G) tag[66] (REP)  =   (R) tag[66] (REP) (by name)
# OUT (G) tag[65] (REP)  =   (R) tag[65] (REP) (by name)
# OUT (G) tag[64] (REP)  =   (R) tag[64] (REP) (by name)
# OUT (G) tag[63] (REP)  =   (R) tag[63] (REP) (by name)
# OUT (G) tag[62] (REP)  =   (R) tag[62] (REP) (by name)
# OUT (G) tag[61] (REP)  =   (R) tag[61] (REP) (by name)
# OUT (G) tag[60] (REP)  =   (R) tag[60] (REP) (by name)
# OUT (G) tag[59] (REP)  =   (R) tag[59] (REP) (by name)
# OUT (G) tag[58] (REP)  =   (R) tag[58] (REP) (by name)
# OUT (G) tag[57] (REP)  =   (R) tag[57] (REP) (by name)
# OUT (G) tag[56] (REP)  =   (R) tag[56] (REP) (by name)
# OUT (G) tag[55] (REP)  =   (R) tag[55] (REP) (by name)
# OUT (G) tag[54] (REP)  =   (R) tag[54] (REP) (by name)
# OUT (G) tag[53] (REP)  =   (R) tag[53] (REP) (by name)
# OUT (G) tag[52] (REP)  =   (R) tag[52] (REP) (by name)
# OUT (G) tag[51] (REP)  =   (R) tag[51] (REP) (by name)
# OUT (G) tag[50] (REP)  =   (R) tag[50] (REP) (by name)
# OUT (G) tag[49] (REP)  =   (R) tag[49] (REP) (by name)
# OUT (G) tag[48] (REP)  =   (R) tag[48] (REP) (by name)
# OUT (G) tag[47] (REP)  =   (R) tag[47] (REP) (by name)
# OUT (G) tag[46] (REP)  =   (R) tag[46] (REP) (by name)
# OUT (G) tag[45] (REP)  =   (R) tag[45] (REP) (by name)
# OUT (G) tag[44] (REP)  =   (R) tag[44] (REP) (by name)
# OUT (G) tag[43] (REP)  =   (R) tag[43] (REP) (by name)
# OUT (G) tag[42] (REP)  =   (R) tag[42] (REP) (by name)
# OUT (G) tag[41] (REP)  =   (R) tag[41] (REP) (by name)
# OUT (G) tag[40] (REP)  =   (R) tag[40] (REP) (by name)
# OUT (G) tag[39] (REP)  =   (R) tag[39] (REP) (by name)
# OUT (G) tag[38] (REP)  =   (R) tag[38] (REP) (by name)
# OUT (G) tag[37] (REP)  =   (R) tag[37] (REP) (by name)
# OUT (G) tag[36] (REP)  =   (R) tag[36] (REP) (by name)
# OUT (G) tag[35] (REP)  =   (R) tag[35] (REP) (by name)
# OUT (G) tag[34] (REP)  =   (R) tag[34] (REP) (by name)
# OUT (G) tag[33] (REP)  =   (R) tag[33] (REP) (by name)
# OUT (G) tag[32] (REP)  =   (R) tag[32] (REP) (by name)
# OUT (G) tag[31] (REP)  =   (R) tag[31] (REP) (by name)
# OUT (G) tag[30] (REP)  =   (R) tag[30] (REP) (by name)
# OUT (G) tag[29] (REP)  =   (R) tag[29] (REP) (by name)
# OUT (G) tag[28] (REP)  =   (R) tag[28] (REP) (by name)
# OUT (G) tag[27] (REP)  =   (R) tag[27] (REP) (by name)
# OUT (G) tag[26] (REP)  =   (R) tag[26] (REP) (by name)
# OUT (G) tag[25] (REP)  =   (R) tag[25] (REP) (by name)
# OUT (G) tag[24] (REP)  =   (R) tag[24] (REP) (by name)
# OUT (G) tag[23] (REP)  =   (R) tag[23] (REP) (by name)
# OUT (G) tag[22] (REP)  =   (R) tag[22] (REP) (by name)
# OUT (G) tag[21] (REP)  =   (R) tag[21] (REP) (by name)
# OUT (G) tag[20] (REP)  =   (R) tag[20] (REP) (by name)
# OUT (G) tag[19] (REP)  =   (R) tag[19] (REP) (by name)
# OUT (G) tag[18] (REP)  =   (R) tag[18] (REP) (by name)
# OUT (G) tag[17] (REP)  =   (R) tag[17] (REP) (by name)
# OUT (G) tag[16] (REP)  =   (R) tag[16] (REP) (by name)
# OUT (G) tag[15] (REP)  =   (R) tag[15] (REP) (by name)
# OUT (G) tag[14] (REP)  =   (R) tag[14] (REP) (by name)
# OUT (G) tag[13] (REP)  =   (R) tag[13] (REP) (by name)
# OUT (G) tag[12] (REP)  =   (R) tag[12] (REP) (by name)
# OUT (G) tag[11] (REP)  =   (R) tag[11] (REP) (by name)
# OUT (G) tag[10] (REP)  =   (R) tag[10] (REP) (by name)
# OUT (G) tag[9] (REP)  =   (R) tag[9] (REP) (by name)
# OUT (G) tag[8] (REP)  =   (R) tag[8] (REP) (by name)
# OUT (G) tag[7] (REP)  =   (R) tag[7] (REP) (by name)
# OUT (G) tag[6] (REP)  =   (R) tag[6] (REP) (by name)
# OUT (G) tag[5] (REP)  =   (R) tag[5] (REP) (by name)
# OUT (G) tag[4] (REP)  =   (R) tag[4] (REP) (by name)
# OUT (G) tag[3] (REP)  =   (R) tag[3] (REP) (by name)
# OUT (G) tag[2] (REP)  =   (R) tag[2] (REP) (by name)
# OUT (G) tag[1] (REP)  =   (R) tag[1] (REP) (by name)
# OUT (G) tag[0] (REP)  =   (R) tag[0] (REP) (by name)
set_root_module AES_CMAC -Golden
set_root_module AES_CMAC -Revised
set_module_property -instance / -Golden
set_module_property -instance / -Revised
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -flowgraph -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
usage
report_hier_compare_result
report_hier_compare_result -Nonequivalent
report_hier_compare_result -Abort
report_hier_compare_result -Uncompared
#-------------------------------------------------------------------------------
# VERBOSE REPORTING
#-------------------------------------------------------------------------------
# The following Golden modules are not written because of non-matching
# instance names in Revised:
# shiftRows (Instance: inst1/r) (G)
# keyExpansion (Instance: ke) (G)
# subBytes (Instance: inst1/s) (G)
# AES_Encrypt (Instance: inst1) (G)
# addRoundKey (Instance: inst1/addrk1) (G)
# mixColumns (Instance: inst1/m) (G)
#-------------------------------------------------------------------------------
# The following Revised modules are not written because of non-matching
# instance names in Golden:
# remainder_unsigned_441 (Instance: rem_83_38) (R)
#-------------------------------------------------------------------------------
# _END_OF_LEC_HIERARCHICAL_DOFILE_
